### ISSUE TITLE
Feature request: add credits for every flag carrier

### ISSUE THREAD

**Issue by bebehei** [pisto/spaghettimod#4]
In rugby mode, the only reason to pass the flag, is to shoot it over a long range.

Additionally the player, who shoots the flag away, won't get rewarded at the end of a successfull capture. So obviously in the stats the others will have a higher rank with less work.

Could you add a feature, that everyone who carried the flag will get rewarded after a successful capture?

**Comment by pisto** [comment]
ok, will do it at some point

**Comment by bebehei** [comment]
Short question: The 'score'-value which is queryable on most servers via #stats-command. Is this an integer value or a float?

**Comment by pisto** [comment]
I honestly don't know what servers report with that command

**Comment by sauerbraten** [comment]
@bebehei Since #stats is an in-game command, the response is a simple server message which is compiled from ints, floats, and whatever else on the server and sent to the client as a string.

**Comment by Croydon** [comment]
:+1:

**Comment by pisto** [comment]
There is now @illogica hosting pastaland, which has rugby mode. I added for him a "rugbypass" event, as of now he just prints that a pass happened (which is already better that my server config). I talked some weeks ago with @bebehei on how to make such reward, and he suggested something based on distance. I believe that would be unnecessarily complicated in implementation, and hard to grasp for users. I am thinking that probably one could just add a flag point for everyone involved in a flag run.

**Comment by bebehei** [comment]
I'm correct that @illogica is GustavoLaPasta? I've seen Pastaland already. He made some great patches.

> I believe that would be unnecessarily complicated in implementation, and hard to grasp for users. I am thinking that probably one could just add a flag point for everyone involved in a flag run.

:+1: This would be great. He already added some things, which are rewarding a pass.

BTW: @illogica: Are your sources available somewhere?

**Comment by pisto** [comment]
@bebehei yes it's him. he told me sources will be available as a spaghettimod fork (he's a beginner with lua so I don't want to pull just anything he produces into spaghettimod)

**Comment by pisto** [comment]
1685c195e63ca381024070e51f7d3ec8575900d5 at long last
